#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ "$OSTYPE" == darwin* ]]; then
	# fix max open files
	ulimit -n 524288 524288

	# fix run-help for homebrew zsh location?
	unalias run-help
	autoload run-help
	HELPDIR=/usr/local/share/zsh/help
fi

# auto push is dumb
setopt noautopushd

eval `dircolors $HOME/.dircolors`

HOMEBREW_GITHUB_API_TOKEN=0ffa5246afe20e913e094dde0fcc0a154a40e30f

if [[ -a "${HOME}/.zsh/bindkeys.zsh" ]]; then
	source "${HOME}/.zsh/bindkeys.zsh"
fi
source "${HOME}/.zsh/aliases.zsh"
source "${HOME}/.zsh/dev.zsh"
# source "${HOME}/.zsh/rubix.zsh"
source "${HOME}/.zsh/there.zsh"

# source "${HOME}/.zsh/iterm2.zsh"


# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# The following lines were added by compinstall

zstyle ':completion:*' add-space true
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _complete _ignored _match _approximate _prefix
zstyle ':completion:*' condition 1
zstyle ':completion:*' format 'Completing %d...'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' match-original both
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+l:|=* r:|=*'
zstyle ':completion:*' max-errors 2
zstyle ':completion:*' menu select=1
zstyle ':completion:*' original false
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/Users/aaron.meadows/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=100000
setopt appendhistory autocd
bindkey -e
# End of lines configured by zsh-newuser-install
